#!/usr/bin/env bash
set -euo pipefail

# This script generates blog posts from git commit history
BLOG_DIR="docs-site/blog"

# Create blog directory
rm -rf "$BLOG_DIR"
mkdir -p "$BLOG_DIR"

# Write authors file
cat > "$BLOG_DIR/authors.yml" << 'EOPY'
# Author information for autogenerated posts
sunwood:
  name: Sunwood-ai-labs
  url: https://github.com/Sunwood-ai-labs
EOPY

# Iterate through commits in reverse chronological order
git rev-list --reverse HEAD | while read -r rev; do
  # Extract metadata
  date=$(git show -s --format=%cI "$rev")
  title=$(git show -s --format=%s "$rev")
  slug=${rev:0:7}
  # Get diff for commit
  if git rev-parse "${rev}^" >/dev/null 2>&1; then
    diff_text=$(git diff "${rev}^" "$rev")
  else
    # First commit: show commit contents
    diff_text=$(git show "$rev")
  fi
  # Prepare filename
  filename="$BLOG_DIR/${date:0:10}-$slug.md"
  # Write frontmatter and diff
  cat > "$filename" << EOF
---
title: "$title"
date: $date
slug: /blog/$slug/
authors: [sunwood]
---

~~~diff
$diff_text
~~~
EOF
done

echo "Generated $(ls "$BLOG_DIR" | wc -l) blog posts in $BLOG_DIR"