#!/usr/bin/env bash
set -euo pipefail

# This script generates blog posts from git commit history
BLOG_DIR="docs-site/blog"

# Create blog directory
rm -rf "$BLOG_DIR"
mkdir -p "$BLOG_DIR"

# Write authors file
cat > "$BLOG_DIR/authors.yml" << 'EOPY'
# Author information for autogenerated posts
sunwood:
  name: Sunwood-ai-labs
  url: https://github.com/Sunwood-ai-labs
EOPY

# Iterate through commits in reverse chronological order
git rev-list --reverse HEAD | while read -r rev; do
  # Extract metadata
  date=$(git show -s --format=%cI "$rev")
  title=$(git show -s --format=%s "$rev")
  slug=${rev:0:7}
  # Prepare filename
  filename="$BLOG_DIR/${date:0:10}-$slug.md"
  # Write progress report post
  cat > "$filename" << EOF
---
title: "🚀 進捗: $title"
date: $date
slug: /blog/$slug/
authors: [sunwood]
---

こんにちは、Sunwood-ai-labsです😊

## 🔖 コミットメッセージ
- $title

## 🗂️ 変更概要
- 「$title」に基づく変更を適用しました。

## 🚀 次のステップ
- 継続的に改善を進めます。

EOF
done

echo "Generated $(ls "$BLOG_DIR" | wc -l) blog posts in $BLOG_DIR"